set -g default-shell /usr/bin/zsh
run-shell "python3 -c 'import powerline, os; print(os.path.join(os.path.dirname(powerline.__file__), \"bindings/tmux/powerline.conf\"))' 2>/dev/null | xargs -I{} tmux source-file {} 2>/dev/null || true"
set -sg escape-time 0
# remap prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix
# enable true color
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",tmux-256color:Tc"
set -g allow-rename off
